# Toxic Comment Classification

Classifying user comments for moderation with TF-IDF and linear models.

**Result:** The selected Logistic Regression pipeline achieved test F1 = 0.78 and ROC-AUC = 0.87.

**Methods:** NLP, spaCy, TF-IDF, imbalanced classification, pipelines, cross-validation.

> This portfolio version removes course-review correspondence and repetitive instructional text. The analysis, models, and reported metrics are based on the original completed project. The source datasets are not included in this repository.

## 1. Setup and data loading

The target identifies toxic comments. The initial review checks class balance, duplicates, and missing values.

In [86]:
from sklearn.feature_extraction.text import (
    TfidfVectorizer,
    CountVectorizer,
    TfidfTransformer,
)
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    accuracy_score,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    plot_precision_recall_curve,
)
from sklearn.linear_model import (
    LogisticRegression,
    RidgeClassifier,
    SGDClassifier,
)
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    GridSearchCV,
    cross_val_predict,
)
from pandarallel import pandarallel
from tqdm.notebook import tqdm
from pymystem3 import Mystem
from IPython.display import display
import sweetviz as sv
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.utils import shuffle
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import lightgbm as lgb
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from tqdm import notebook, tqdm
import transformers
import torch
from spacy.lang.en import English
import spacy
import warnings
import random
import requests
import string

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import nltk
import re
from nltk.tokenize import word_tokenize, RegexpTokenizer
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords as nltk_stopwords
from nltk.probability import FreqDist
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

nlp = spacy.load("en_core_web_sm")

pandarallel.initialize(progress_bar=True)

warnings.filterwarnings('ignore')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/kolotukhin.md/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kolotukhin.md/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/kolotukhin.md/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

In [87]:
df = pd.read_csv(
    '/Users/kolotukhin.md/Downloads/jupyter_notebook/11/toxic_comments.csv', index_col=0)

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [88]:
data = df.copy()

In [89]:
def get_data_info(data):
    display(data.sample(5))
    display(data.info())

In [90]:
get_data_info(data)

                                                     text  toxic
55284   "\n\nAngkor\nHey I love Cambodia and Angkor to...      0
60614   This album is very similar to Clayman in all a...      0
103751  "\n\n Pope John Paul II Peer review \n\nHi DrK...      0
118377  Welcome!\n\nHello, , and welcome to Wikipedia!...      0
78964   Temazepam\nI reverted your edits since they ap...      0

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159292 entries, 0 to 159450
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   text    159292 non-null  object
 1   toxic   159292 non-null  int64
dtypes: int64(1), object(1)
memory usage: 3.6+ MB

None

In [91]:
def check_balance(data):
    print(round((data['toxic'].value_counts(normalize=True)), 3))

check_balance(data)

0    0.898
1    0.102
Name: toxic, dtype: float64

In [92]:
ratio = data['toxic'].value_counts(normalize=(0, 1))
ratio.plot(kind='bar', grid=True)
plt.xlabel("Comment class")
plt.ylabel("Proportion")
plt.title("Toxic versus non-toxic comments")
plt.show()

In [93]:
display(data['toxic'].value_counts())
class_ratio = data['toxic'].value_counts()[0] / data['toxic'].value_counts()[1]

0    143106
1     16186
Name: toxic, dtype: int64

In [94]:
print(data.duplicated().value_counts())

False    159292
dtype: int64

In [95]:
display(data.isnull().sum())

text     0
toxic    0
dtype: int64

## 2. Text preprocessing

Text is normalised and lemmatised with spaCy before vectorisation.

In [96]:
def clean_text(text):
    clean = nlp(" ".join(re.sub(r'[^a-zA-z]', ' ', text).split()))
    lemmatized_output = ' '.join([w.lemma_ for w in clean])
    return lemmatized_output

In [97]:
data['spacy_lemmatize'] = data['text'].parallel_apply(clean_text)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=39823), Label(value='0 / 39823')))…

In [98]:
data = data.drop(['text'], axis=1)

In [99]:
get_data_info(data)

        toxic                                    spacy_lemmatize
148044      0  how have I harm those page you be waste my tim...
103729      0  the t and the h be more or less silent give sk...
15117       0  you list feminism as the prominent advocate ag...
80449       0  unfortunately not it s the same questionable r...
122591      0  that s an interesting point actually I m not t...

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159292 entries, 0 to 159450
Data columns (total 2 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   toxic            159292 non-null  int64
 1   spacy_lemmatize  159292 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.6+ MB

None

## 3. Exploratory text analysis

Word clouds and frequency distributions are used as descriptive checks rather than modelling inputs.

In [100]:
data_words = data.copy()

In [101]:
text = ' '.join(data_words['spacy_lemmatize'])

In [102]:
FIG_SIZE = (17, 13)

In [103]:
# Generate the word cloud
cloud = WordCloud().generate(text)

# Plot the word cloud
plt.figure(figsize=FIG_SIZE)
plt.imshow(cloud, interpolation='bilinear', cmap='coolwarm')
plt.axis('off')
plt.title('Word Cloud of Text Data', fontsize=20)
plt.show()

# Save the plot to a file
plt.savefig('word_cloud.png', dpi=300, bbox_inches='tight')

In [104]:
# Generate the matrix data
cloud = WordCloud().generate(text)

# Plot the matrix
fig, ax = plt.subplots(figsize=FIG_SIZE)
ax.matshow(cloud, interpolation='bilinear', cmap='coolwarm')
ax.set_title('Matrix Plot of Text Data', fontsize=20)
plt.axis('off')
plt.show()

# Save the plot to a file
fig.savefig('matrix_plot.png', dpi=300, bbox_inches='tight')

In [105]:
type(text)

str

In [106]:
len(text)

57483708

In [107]:
text = text.lower()

In [108]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [109]:
type(string.punctuation)

str

In [110]:
spec_chars = string.punctuation + '\n\xa0«»\t—…'

In [111]:
text = "".join([ch for ch in text if ch not in spec_chars])

In [112]:
text = re.sub('\n', '', text)

In [113]:
def remove_chars_from_text(text, chars):
    return "".join([ch for ch in text if ch not in chars])

In [114]:
text = remove_chars_from_text(text, spec_chars)

In [115]:
text = remove_chars_from_text(text, string.digits)

In [116]:
text_tokens = word_tokenize(text)

In [117]:
print(type(text_tokens), len(text_tokens))
text_tokens[:10]

<class 'list'> 10843917

['explanation',
 'why',
 'the',
 'edit',
 'make',
 'under',
 'my',
 'username',
 'hardcore',
 'metallica']

In [118]:
text = nltk.Text(text_tokens)
print(type(text))
text[:10]

<class 'nltk.text.Text'>

['explanation',
 'why',
 'the',
 'edit',
 'make',
 'under',
 'my',
 'username',
 'hardcore',
 'metallica']

In [119]:
fdist = FreqDist(text)
fdist

FreqDist({'the': 495736, 'be': 458567, 'to': 297478, 'i': 278853, 'of': 224030, 'and': 223449, 'you': 218399, 'a': 216854, 'that': 161241, 'it': 148272, ...})

In [120]:
fdist.most_common(5)

[('the', 495736),
 ('be', 458567),
 ('to', 297478),
 ('i', 278853),
 ('of', 224030)]

In [121]:
plt.figure(figsize=(15, 7))
fdist.plot(30, cumulative=False)
plt.show()

In [123]:
from nltk.corpus import stopwords

# Now you can use the stopwords module
english_stopwords = stopwords.words("english")

# You can also remove stopwords from text using these stopwords

In [124]:
english_stopwords = stopwords.words("english")

In [125]:
print(len(english_stopwords))

179

In [126]:
text_tokens = [token.strip()
               for token in text_tokens if token not in english_stopwords]

In [127]:
print(len(text_tokens))

5488673

In [128]:
text = nltk.Text(text_tokens)

In [129]:
fdist_sw = FreqDist(text)
fdist_sw.most_common(10)

[('article', 72923),
 ('page', 56856),
 ('wikipedia', 48346),
 ('talk', 39694),
 ('edit', 37120),
 ('use', 33013),
 ('one', 30624),
 ('make', 30371),
 ('please', 29771),
 ('would', 29336)]

In [130]:
plt.figure(figsize=(15, 7))
fdist_sw.plot(30, cumulative=False)
plt.show()

## 4. Train/test split and vectorisation

The split is performed before TF-IDF fitting to avoid information leakage.

In [131]:
target = data['toxic']

features = data['spacy_lemmatize']

In [132]:
stop_words = set(stopwords.words('english'))

In [133]:
features_train, features_valid_test, target_train, target_valid_test = train_test_split(features,
                                                                                        target,
                                                                                        test_size=0.4,
                                                                                        random_state=12345,
                                                                                        stratify=target
                                                                                        )

features_valid, features_test, target_valid, target_test = train_test_split(features_valid_test,
                                                                            target_valid_test,
                                                                            test_size=0.5,
                                                                            random_state=12345,
                                                                            stratify=target_valid_test
                                                                            )

In [134]:
CV_COUNTS = 3

In [135]:
features_train.info()

<class 'pandas.core.series.Series'>
Int64Index: 95575 entries, 129844 to 11556
Series name: spacy_lemmatize
Non-Null Count  Dtype
--------------  -----
95575 non-null  object
dtypes: object(1)
memory usage: 1.5+ MB

In [136]:
print(features_train.shape)
print(features_valid.shape)
print(features_test.shape)
print()
print(target_train.shape)
print(target_valid.shape)
print(target_test.shape)

(95575,)
(31858,)
(31859,)

(95575,)
(31858,)
(31859,)

## 5. Model selection

Several linear and gradient-boosting classifiers are compared with cross-validation. F1 is the selection metric because the toxic class is imbalanced.

In [137]:
np.random.seed(42)

In [138]:
# TfidfVectorizer()

params = {'model__C': np.logspace(.5, 5, 10, 15),
          'model__class_weight': ['balanced', None]
          }

tfidf_vectorizer = TfidfVectorizer(stop_words=stop_words,
                                   ngram_range=(1, 2)
                                   )

pipeline = Pipeline([('tfidf_vectorizer', tfidf_vectorizer),
                     ('model', LogisticRegression(random_state=42))
                     ]
                    )

grid_LR = GridSearchCV(pipeline,
                       n_jobs=-1,
                       param_grid=params,
                       cv=CV_COUNTS,
                       scoring='f1'
                       )

grid_LR.fit(features_train, target_train)
print("Best parameters set found on development set:")
print()
print(grid_LR.best_params_)
print()
cv_F1_LR = grid_LR.best_score_
print('best_score F1:', round(cv_F1_LR, 2))

/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Best parameters set found on development set:

{'model__C': 316.22776601683796, 'model__class_weight': 'balanced'}

best_score F1: 0.78

In [139]:
params = {'model__alpha': [0.05, 0.1, 0.2, 0.4, 1]}

pipeline = Pipeline([('tfidf_vectorizer', TfidfVectorizer(stop_words=stop_words,
                                                          ngram_range=(1, 2))),
                     ('model', RidgeClassifier(random_state=42))
                     ]
                    )

grid_RC = GridSearchCV(pipeline,
                       n_jobs=-1,
                       param_grid=params,
                       cv=CV_COUNTS,
                       scoring='f1'
                       )

grid_RC.fit(features_train, target_train)
print("Best parameters set found on development set:")
print()
print(grid_RC.best_params_)
print()
cv_F1_RC = grid_RC.best_score_
print('best_score F1:', round(cv_F1_RC, 2))

Best parameters set found on development set:

{'model__alpha': 0.4}

best_score F1: 0.74

In [140]:
params = {'model_SGDC__max_iter': np.arange(2, 100, 10)}


pipeline = Pipeline([('tfidf_vectorizer', TfidfVectorizer(stop_words=stop_words,
                                                          ngram_range=(1, 2))),
                     ('model_SGDC', SGDClassifier(random_state=42))
                     ]
                    )

grid_SGDC = GridSearchCV(pipeline,
                         n_jobs=-1,
                         param_grid=params,
                         cv=CV_COUNTS,
                         scoring='f1'
                         )

grid_SGDC.fit(features_train, target_train)
print("Best parameters set found on development set:")
print()
print(grid_SGDC.best_params_)
print()
cv_F1_SGDC = grid_SGDC.best_score_
print('best_score F1:', round(cv_F1_SGDC, 2))

/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py:705: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py:705: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
/Users/anaconda/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_stochastic_gradient.py:705: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

Best parameters set found on development set:

{'model_SGDC__max_iter': 12}

best_score F1: 0.59

In [141]:
grid_params = {'model_LGBM__max_depth': np.arange(10, 200, 100),
               'model_LGBM__reg_alpha': np.linspace(0, 1)
               }

pipe_LGBM = Pipeline(steps=[('tfidf', TfidfVectorizer(stop_words=stop_words,
                                                      ngram_range=(1, 1))),
                            ('model_LGBM', LGBMClassifier(random_state=42))
                            ]
                     )

print('# Tuning hyper-parameters for F1')
print()
clf_LGBM = GridSearchCV(estimator=pipe_LGBM,
                        param_grid=grid_params,
                        n_jobs=-1,
                        cv=CV_COUNTS,
                        scoring='f1')

clf_LGBM.fit(features_train, target_train)
print("Best parameters set found on development set:")
print()
print(clf_LGBM.best_params_)
print()
cv_F1_LGBM = clf_LGBM.best_score_
print('best_score F1:', round(cv_F1_LGBM, 2))

# Tuning hyper-parameters for F1

Best parameters set found on development set:

{'model_LGBM__max_depth': 110, 'model_LGBM__reg_alpha': 0.1020408163265306}

best_score F1: 0.75

In [142]:
plt.figure(figsize=[12, 9])

plt.plot([0, 1], [0, 1], linestyle='--', label='RandomModel')

probabilities_valid = grid_LR.best_estimator_.predict(features_valid)
probabilities_one_valid = probabilities_valid
fpr, tpr, thresholds = roc_curve(target_valid, probabilities_one_valid)
auc_roc_LR = roc_auc_score(target_valid, probabilities_one_valid)
F1_LR = f1_score(target_valid, grid_LR.predict(features_valid))
plt.plot(fpr, tpr, label='LogisticRegression (Pipeline + GridSearchCV)')

probabilities_valid = grid_RC.best_estimator_.predict(features_valid)
probabilities_one_valid = probabilities_valid
fpr, tpr, thresholds = roc_curve(target_valid, probabilities_one_valid)
auc_roc_RC = roc_auc_score(target_valid, probabilities_one_valid)
F1_RC = f1_score(target_valid, grid_RC.predict(features_valid))
plt.plot(fpr, tpr, label='RidgeClassifier (Pipeline + GridSearchCV)')

probabilities_valid = grid_SGDC.best_estimator_.predict(features_valid)
probabilities_one_valid = probabilities_valid
fpr, tpr, thresholds = roc_curve(target_valid, probabilities_one_valid)
auc_roc_SGDC = roc_auc_score(target_valid, probabilities_one_valid)
F1_SGDC = f1_score(target_valid, grid_SGDC.predict(features_valid))
plt.plot(fpr, tpr, label='SGDClassifier (Pipeline + GridSearchCV)')

probabilities_valid = clf_LGBM.best_estimator_.predict(features_valid)
probabilities_one_valid = probabilities_valid
fpr, tpr, thresholds = roc_curve(target_valid, probabilities_one_valid)
auc_roc_LGBMC = roc_auc_score(target_valid, probabilities_one_valid)
F1_LGBM = f1_score(target_valid, clf_LGBM.predict(features_valid))
plt.plot(fpr, tpr, label='LGBMClassifier (Pipeline + GridSearchCV)')

plt.xlim([0, 1])
plt.ylim([0, 1])

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.legend(loc='lower right', fontsize='x-large')

plt.title("ROC curve")
plt.show()

In [143]:
index = ['LogisticRegression (Pipeline + GridSearchCV)',
         'RidgeClassifier (Pipeline + GridSearchCV)',
         'SGDClassifier (Pipeline + GridSearchCV)',
         'LGBMClassifier (Pipeline + GridSearchCV)'
         ]

data = {'F1 (CV)': [round(F1_LR, 2),
                     round(F1_RC, 2),
                     round(F1_SGDC, 2),
                     round(F1_LGBM, 2)
                     ],

        'AUC-ROC': [round(auc_roc_LR, 2),
                    round(auc_roc_RC, 2),
                    round(auc_roc_SGDC, 2),
                    round(auc_roc_LGBMC, 2)
                    ]
        }

scores_data = pd.DataFrame(data=data, index=index)
scores_data

## 6. Held-out evaluation

Only the selected Logistic Regression pipeline is evaluated on the test set. ROC-AUC is calculated from predicted probabilities, not hard class labels.

In [144]:
# Final evaluation of the selected model only
selected_model = grid_LR.best_estimator_
test_predictions = selected_model.predict(features_test)
test_probabilities = selected_model.predict_proba(features_test)[:, 1]

test_f1 = f1_score(target_test, test_predictions)
test_roc_auc = roc_auc_score(target_test, test_probabilities)
print(f"Test F1: {test_f1:.2f}")
print(f"Test ROC-AUC: {test_roc_auc:.2f}")

fpr, tpr, _ = roc_curve(target_test, test_probabilities)
plt.figure(figsize=(10, 7))
plt.plot(fpr, tpr, label=f"Logistic Regression (AUC = {test_roc_auc:.2f})")
plt.plot([0, 1], [0, 1], linestyle="--", label="Random baseline")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC curve")
plt.legend(loc="lower right")
plt.show()

## Conclusion

Logistic Regression provided the strongest validation performance and met the required F1 threshold on the held-out test set. The model is a transparent, efficient baseline for moderation; threshold tuning should follow the desired balance between moderator workload and missed toxic content.